Add bowling file
shirotamaki/ruby-practices pull request #8
Opened 2021-02-20 02:02 UTC by shirotamaki

ボウリング課題が完成しました🎳
ご確認お願いいたします！

2021-02-24 13:00 UTC, u1tnk requested changes

2021-02-24 13:00 UTC, u1tnk commented on 04.bowling/bowling.rb
> +  if frame_count == 10 && shot_count == 1 && s == 10
ここは以下のようにネストしちゃった方が見やすくなりますね。

```
if frame_count == 10 
  if shot_count == 1 && s == 10
  ....
  else
  ...
  end
  brank

end
```

2021-02-24 13:00 UTC, u1tnk commented on 04.bowling/bowling.rb
> +scores.each do |s|
以下のようにmapを使うと綺麗に書けるのでやってみてください 💪 
```
shots = scores.map ...
略
```

2021-02-25 09:09 UTC, shirotamaki commented on 04.bowling/bowling.rb
> +scores.each do |s|
かしこまりました。
mapを使い修正しました✍️

2021-02-25 09:10 UTC, shirotamaki commented on 04.bowling/bowling.rb
> +  if frame_count == 10 && shot_count == 1 && s == 10
かしこまりました。
ネストにして修正しました✍️

2021-02-25 12:25 UTC, u1tnk requested changes

2021-02-25 12:25 UTC, u1tnk commented on 04.bowling/bowling.rb
> +    elsif frame_count == 10 && frame_score == 10
` if frame_count == 10 ` のブロックの中なのでここでは不要です。

2021-02-25 12:25 UTC, u1tnk commented on 04.bowling/bowling.rb
> +shots = scores.map { |s| s == 'X' ? 10 : s.to_i }
スッキリしましたね 👍

2021-02-26 04:39 UTC, shirotamaki commented on 04.bowling/bowling.rb
> +    elsif frame_count == 10 && frame_score == 10
29行目の `frame_count == 10`　削除しました！

2021-02-26 06:31 UTC, merged